### ISSUE TITLE
Cocoapods support

### ISSUE THREAD

**Issue by dominik-hadl** [tonystone/tracelog-adaptive-writer#8]
Are you planning on adding support for CocoaPods for this package? It would simplify the installation process and wouldn't require me to use two different package managers.

**Comment by tonystone** [comment]
@nickskull Yes, I'll be releasing that shortly.

Also, sorry for the delay, missed this one in my email.

Update:

@nickskull Just a quick update, I'll be releasing the CocoaPods version in the next day or so.  I decided to add that to the first non-beta release that I'm already doing.

**Comment by tonystone** [comment]
@nickskull CocoaPods version 1.0.0 published, let me know if you have any issues.

**Comment by dominik-hadl** [comment]
Works great, thanks!
